### ISSUE TITLE
Kingfisher Theme 

### ISSUE THREAD

**Issue by maulik-biztech** [eiqui-dev/eiqui#1]
Hi There,

Can you pls take down the Kingfisher theme from your repo which is made available to public ? We understand, it might have happened out of some mistake. The theme is available for purchase at https://www.odoo.com/apps/themes/9.0/kingfisher/

Would be helpful if you can confirm once its removed. Let me know if any concerns!

Best,
Maulik Shah
CEO, Biztech IT Consultancy Pvt. Ltd.
maulik@biztechconsultancy.com

**Comment by DarioLodeiros** [comment]
Sorry,  but our customers has public services with this module,  and we must have public this code according to the GPL license which are subject to be derivative works from version 8.0 Odoo. Sorry for the inconvenience but the license is clear about it.

**Comment by maulik-biztech** [comment]
Dear Dario,

The Kingfisher theme is not open source. You can only modify it to suits
your own needs and use it for yourself, but you cannot modify it then
redistribute it in any way.

Pls. immediately take it down else we will be forced to report this in Odoo
as well as file DMCA takedown procedure with Github.

Best Regards,
Maulik

_Maulik Shah_
CEO, Biztech IT Consultancy Pvt. Ltd.
_Mobile:_ +91 9879622024  |  _Email:_ maulik@biztechconsultancy.com
_Skype_: maulik_biztech  |  _gTalk:_ maulik.9@gmail.com
www.biztechconsultancy.com

**Comment by DarioLodeiros** [comment]
Isn't kingfischer based on odoo 8.0?? Becouse we use it in 8.0 v and this version has a AGPL license., it means that any derivated work  os subject to this license. 
Sorry de inconvenience.  We do not want to hurt your work,  but if you dont undertand this web must public this question in the OCA community to resolve it.

**Comment by maulik-biztech** [comment]
I don't think that's correct as you can't just make any Paid work public.

Hi David,

Can you pls. help looking in to this ?

​
Best Regards,
Maulik

_Maulik Shah_
CEO, Biztech IT Consultancy Pvt. Ltd.
_Mobile:_ +91 9879622024  |  _Email:_ maulik@biztechconsultancy.com
_Skype_: maulik_biztech  |  _gTalk:_ maulik.9@gmail.com
www.biztechconsultancy.com

**Comment by DarioLodeiros** [comment]
https://en.m.wikipedia.org/wiki/Affero_General_Public_License
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)#changesets/active
https://www.odoo.com/es_ES/page/legal (view the 8.0 section) 
Im sorry for the inconvenience

**Comment by maulik-biztech** [comment]
+David from Odoo

​I hope this helps. Let me know if any concerns!

Best Regards,
Maulik

_Maulik Shah_
CEO, Biztech IT Consultancy Pvt. Ltd.
_Mobile:_ +91 9879622024  |  _Email:_ maulik@biztechconsultancy.com
_Skype_: maulik_biztech  |  _gTalk:_ maulik.9@gmail.com
www.biztechconsultancy.com

**Comment by Tardo** [comment]
Conflictive modules removed.
